

jobs:

- job: WindowsBuild
  displayName: "Windows build"
  pool:
    vmImage: "windows-latest"
  steps:
    - script: dotnet build
    - script: dotnet test

- job: Release 
  displayName: Create Release
  dependsOn: 
  - Build
  steps:
  - task: DownloadPipelineArtifact@0
    inputs:
     artifactName: 'WindowsBuild'
     targetPath: tmp
  - task: GitHubRelease@0
    inputs:
      gitHubConnection: NikolajBjorner
      repositoryName: 'NikolajBjorner/NikolajBjorner.srm'
      action: 'create'
#     target: '$(Build.SourceVersion)'
      tagSource: 'manual'
      tag: 'Build'
      title: 'Build'
      releaseNotesSource: 'input'
      releaseNotes: 'build release'
      assets: 'tmp/*'
      assetUploadMode: 'replace'
      isDraft: false
      isPreRelease: true
