trigger: none

variables:
  ReleaseVersion: '2.0.0-alpha3'

pool:
  vmImage: "windows-latest"

steps:
- script: dotnet build srm --configuration Release -p:BuildType=Official -p:Version=$(ReleaseVersion) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Build'
- task: EsrpCodeSigning@1
  displayName: 'StrongName sign'
  inputs:
    ConnectedServiceName: 'srm-esrp-signing'
    FolderPath: $(Build.ArtifactStagingDirectory)
    Pattern: srm.dll
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [
          {
              "KeyCode" : "CP-233863-SN",
              "OperationCode" : "StrongNameSign",
              "Parameters" : {},
              "ToolName" : "sign",
              "ToolVersion" : "1.0"
          },
          {
              "KeyCode" : "CP-233863-SN",
              "OperationCode" : "StrongNameVerify",
              "Parameters" : {},
              "ToolName" : "sign",
              "ToolVersion" : "1.0"
          }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'
- script: dotnet pack srm -p:PackageVersion=$(ReleaseVersion) --output $(Build.ArtifactStagingDirectory) --no-build -p:OutputPath=$(Build.ArtifactStagingDirectory)
  displayName: 'Pack'
- task: EsrpCodeSigning@1
  displayName: 'NuGet sign'
  inputs:
    ConnectedServiceName: 'srm-esrp-signing'
    FolderPath: $(Build.ArtifactStagingDirectory)
    Pattern: Microsoft.Automata.SRM.$(ReleaseVersion).nupkg
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [
        {
          "KeyCode" : "CP-401405",
          "OperationCode" : "NuGetSign",
          "Parameters" : {},
          "ToolName" : "sign",
          "ToolVersion" : "1.0"
        },
        {
          "KeyCode" : "CP-401405",
          "OperationCode" : "NuGetVerify",
          "Parameters" : {},
          "ToolName" : "sign",
          "ToolVersion" : "1.0"
        }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(Build.ArtifactStagingDirectory)\Microsoft.Automata.SRM.$(ReleaseVersion).nupkg
    artifactName: 'NuGetPackage'